/*
 * Bonito Register Map
 * Copyright (c) 1999 Algorithmics Ltd
 *
 * Algorithmics gives permission for anyone to use and modify this file
 * without any obligation or license condition except that you retain
 * this copyright message in any source redistribution in whole or part.
 *
 * Updated copies of this and other files can be found at
 * ftp://ftp.algor.co.uk/pub/bonito/
 *
 * Users of the Bonito controller are warmly recommended to contribute
 * any useful changes back to Algorithmics (mail to
 * bonito@algor.co.uk).
 */

/* Revision 1.48 autogenerated on 08/17/99 15:20:01 */

#ifndef _BONITO_H_
#define _BONITO_H_
#include "cpu.h"

//#define	NS16550HZ	1843200
#define	NS16550HZ		3686400

#define COM1_BASE_ADDR		LS2K0300_UART0_REG_BASE		//for fpga 
#define COM3_BASE_ADDR		LS2K0300_UART0_REG_BASE		//for newdebug.S

#define BONITO_FLASH_BASE		PHYS_TO_UNCACHED(0x1c000000)
#define BONITO_FLASH_SIZE		0x100000

#define LOCK_CACHE_BASE			PHYS_TO_CACHED(0x90000000)
#define LOCK_CACHE_SIZE			0x40000	//256KB
#endif /* _BONITO_H_ */
